logging:
  level:
    web: INFO
    root: INFO

spring:
  rsocket:
    server:
      port: 6565
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/postgres
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s