logging:
  level:
    web: INFO
    root: INFO

server:
  port: 8089

spring:
  rsocket:
    server:
     # ssl:
     #   enabled: true
     #   key-store-type: PKCS12
     #   key-store: /home/spark/Documentos/repo/webflux-examples/rsocket-server.p12
     #   key-store-password: password
     #   key-alias: rsocket
      port: 6565
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/postgres
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s